version: '3.5'

services:
  db:
    image: postgres:13-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env.db
  web:
    image: mcodegeeks/portfolio:latest
    container_name: web
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - static_volume:/var/www/staticfiles/
      - media_volume:/var/www/mediafiles/
    env_file:
      - .env
    depends_on:
      - db
  nginx:
    image: mcodegeeks/nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - static_volume:/var/www/staticfiles/
      - media_volume:/var/www/mediafiles/
    depends_on:
      - web

volumes:
  postgres_volume:
  static_volume:
  media_volume: