version: '3.5'

services:
  db:
    image: postgres:13-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "54320:5432"
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_volume: